version: "3"
services:
  routeros:
    image: evilfreelancer/docker-routeros:7.1beta6
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    networks:
      bradius:
        ipv4_address: 192.168.100.250
    ports:
      - "8291:8291"
    volumes:
      - "./routeros/chr.vdi:/routeros/chr-7.1beta6.vdi"
networks:
  bradius:
    name: "bridge-radius"
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
          gateway: 192.168.100.1

